---
language: ruby

rvm:
  - 2.1.9

env:
  matrix:
    - RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 4.7.0"
    - RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 4.8.0"
    - RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 4.9.0"
    - RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 4.10.0"
    - RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 4"

sudo: false

before_install:
  - if [ $BUNDLER_VERSION ]; then
      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
    fi
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v

script: 'SPEC_OPTS="--format documentation" bundle exec rake test'

matrix:
  fast_finish: true

notifications:
  email: false
